org: unikraft
name: sig-sched
description: Unikraft Schedulers Special Interest Group
privacy: closed

maintainers:
  - name: Simon Kuenzer
    github: skuenzer

reviewers:
  - name: Sergiu Moga
    github: mogasergiu
  - name: Dragoș Argint
    github: dragosargint
  - name: Daniel Dincă
    github: danield20

repos:
  - name: lib-pthread-embedded
  - name: lib-pthreadpool
